# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://localhost:4000
#url: http://yoursite.com
title: Mr Cozzens
email: 
author: Mr Cozzens
description: > # "Write an awesome description for your new site here. 
  Personal site for Mr Cozzens. Currently on GH-Pages
copyright: 'Copyright &copy; 2019 Mr Cozzens. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: https://www.linkedin.com
